### ISSUE TITLE
Progress bar in nl2code_train

### ISSUE THREAD

**Issue by Vafa-Andalibi** [HiroakiMikami/mlprogram#37]
Hi, Is there any progress bar when running the `python tools/launch.py -c configs/hearthstone/nl2code_train.gin` ? 
I can't tell whether it's running or the code hangs in my environment.

**Comment by Vafa-Andalibi** [comment]
Just found out that I can track the progress through output folder: 
`$ watch -n 1 tree output`

**Comment by HiroakiMikami** [comment]
Thank you for having an interest in this repository! And sorry for the late reply.

A moment ago, I changed the implementation. The script shows a progress bar during training and evaluation after this change.
Because I replaced the config format from gin to yaml,  please notes that the command to train nl2code is`python tools/launch.py -c configs/hearthstone/nl2code_train.yaml`.
